[build]
  command = "node server.js"
  publish = "views"  # 만약 정적 파일이 다른 디렉토리에 있다면 해당 디렉토리로 변경

[dev]
  command = "node server.js"
  port = 3000  # Express 앱이 사용하는 포트 번호

[context.production]
  command = "node server.js"
  port = 3000  # Express 앱이 사용하는 포트 번호

[context.deploy-preview]
  command = "node server.js"
  port = 3000  # Express 앱이 사용하는 포트 번호

[context.branch-deploy]
  command = "node server.js"
  port = 3000  # Express 앱이 사용하는 포트 번호